import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Chats from "./chats";
import Sidebar from "./components/sidebar";
import OneChat from "./chats/oneChat";
import { getProviders, getSession, useSession } from 'next-auth/react'
import Login from "./components/login";

const Home: NextPage = ({  providers }) => {
  const { data: session } = useSession()
  if (!session) return <Login providers={providers}/>
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>MyChat</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
       <div className="">
      <Sidebar/>
      </div> 
    </>
  );
};

export default Home;
export async function getServerSideProps(context) {
  const trendingResults = await fetch('https://jsonkeeper.com/b/NKEV').then(
    res => res.json()
  )
  const followResults = await fetch('https://jsonkeeper.com/b/WWMJ').then(res =>
    res.json()
  )
  const providers = await getProviders()
  // const session = await getSession(context)

  return {
    props: {
      trendingResults,
      followResults,
      providers,
      // session,
    },
  }
}